// lib/utils/firebase_config.dart

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class FirebaseConfig {
  static Future<void> initialize() async {
    if (kIsWeb) {
      // Web configuration
      await Firebase.initializeApp(
        options: const FirebaseOptions(
          apiKey: "YOUR_API_KEY",
          authDomain: "YOUR_PROJECT_ID.firebaseapp.com",
          projectId: "YOUR_PROJECT_ID",
          storageBucket: "YOUR_PROJECT_ID.appspot.com",
          messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
          appId: "YOUR_APP_ID",
        ),
      );
    } else {
      // Mobile configuration (will be auto-generated by flutterfire configure)
      await Firebase.initializeApp();
    }
  }
}

// Collection names - centralized for easy management
class FirebaseCollections {
  static const String users = 'users';
  static const String assessments = 'assessments';
  static const String programs = 'programs';
  static const String enrollments = 'enrollments';
  static const String progress = 'progress';
}